### ISSUE TITLE
Patches changelog?

### ISSUE THREAD

**Issue by BarbzYHOOL** [TheFakeMateo/RedPlusPlus#110]
What are the new features included in https://github.com/TheFakeMateo/RedPlusPlus/tree/master/patches ? (like hard mode, nuzlocke etc)

**Comment by TheFakeMateo** [comment]
Forgot I even had a patches folder in this repo. If you're looking for the latest playable releases, you should look here instead: https://github.com/TheFakeMateo/rpp-backup/tree/master/patches

I do not have a changelog posted on here though.
