### ISSUE TITLE
Help Adding More Than 152 Pokemon

### ISSUE THREAD

**Issue by ChefFloyardee** [TheFakeMateo/RedPlusPlus#129]
Hi!

I am working on my own hack of Pokered, and I am stuck on adding a 153rd mon.

I added a 152nd just fine and it works, but when I try to add more than that I get fully working mon with MISSINGNO sprites that never change no matter what I do.

Could you please provide me with some insight for how to take the original Pokered and change it to get fully working 153+ mon? 

Let me know ;D

**Comment by Rangi42** [comment]
This isn't even a pokered-based hack any more, and GitHub issue pages are for problems with this project, not some other game. Try asking on the pret #pokered Discord, or Skeetendo forums.

**Comment by ChefFloyardee** [comment]
I apologize.

I am just getting frustrated and trying to ask for the help of as many people as I can.

I tried the Discord but no one seemed to know there, and I also made a post on the forum.

Would you happen to know how to do this though? I've followed Danny-E's Glaceon tutorial but it still will not work for me.

**Comment by Rangi42** [comment]
I can understand asking more people for help, but there's nobody new here. And I can help with pokecrystal, but not pokered.

**Comment by ChefFloyardee** [comment]
Do you know anyone who would know what to do to Pokered to get 153+ Pokemon?
