### ISSUE TITLE
SHARPEN on Chameleon?

### ISSUE THREAD

**Issue by Fighter19** [TheFakeMateo/RedPlusPlus#16]
I just leveled up my Chameleon and found it wants to learn Sharpen, which actually is a Porygon move.
Is this just a left-over from debugging or is this intended?

**Comment by TheFakeMateo** [comment]
Absolutely 100% intended. A lot of Pokémon learn Sharpen as a stand-in for Hone Claws.

**Comment by Fighter19** [comment]
You mean in this case for Scary Face?

**Comment by TheFakeMateo** [comment]
It's at the level he would learn it, but since there wasn't a good stand-in, I went with this since Hone Claws is a move they can learn by TM. In the future I'm just going to rename Sharpen to Hone Claws and update the effect, since I have a lot of Pokémon learning it like it was Hone Claws.
