### ISSUE TITLE
Error 5

### ISSUE THREAD

**Issue by Jaxor** [TheFakeMateo/RedPlusPlus#21]
I'm trying to do this on a windows computer and I'm really bad at these sorts of things. I tried to follow the video tutorial as best as I could, with the exception of using updated versions and using the "Python 2" versions. However, when I put in the "Make" command after loading it once, it just gives me this error:

$ make
rgbasm -D _RED -h -o wram_red.o wram.asm
ERROR: wram.asm(3309):
        Constant mustn't be negative: -2
make: *** [Makefile:37: wram_red.o] Error 5

And to be clear, it gave me this message on first load-up as well.

**Comment by TheFakeMateo** [comment]
That's the problem -- you used newer versions. INSTALL.md lists a specific version of RGBDS for you to use. Newer versions of RGBDS no longer support pokered and pokecrystal, so you have to use the version we list in the instructions.

**Comment by Jaxor** [comment]
So, I replaced the new version with rgdbs 0.2.5 and it gives me Error 1:

rgbasm -D _RED -h -o wram_red.o wram.asm
rgblink -n pokered.sym -o pokered.gbc audio_red.o main_red.o text_red.o wram_red.o
C:\Users\Jaxon\Desktop\Cygwin\usr\local\bin\rgblink.exe: 'audio_red.o' is an unsupported version
make: *** [Makefile:47: pokered.gbc] Error 1

And just a side question, what is the benefit of doing this instead of using the .ips patch?

**Comment by TheFakeMateo** [comment]
Sounds like you have leftover converted and partially converted files from where you tried to build it with the wrong version at first. Try running "make clean" and then trying "make" again.

**Comment by Jaxor** [comment]
Worked! Thanks a bunch! But I am still curious as to what the benefit is to doing this over just using the .ips patch?

**Comment by TheFakeMateo** [comment]
If all you want to do is play it, there really is no benefit other than getting the absolute latest (and therefore potentially unstable depending on what I'm working on) version, so some people will do it to point out bugs in things I'm working on. But as for actually making the hack, this way is infinitely better than hacking the normal rom with a bunch of old fashioned tools.
