### ISSUE TITLE
Flash referred to as an HM

### ISSUE THREAD

**Issue by ZephaniahNoah** [TheFakeMateo/RedPlusPlus#32]
When you go to PROF.OAK's PC he tells you to get flash but calls it an HM even though it's a TM now.
![flash is a tm](https://user-images.githubusercontent.com/14168013/33584353-c5c000c6-d913-11e7-9f0b-4011ae14b54c.png)

**Comment by TheFakeMateo** [comment]
This has already been fixed in master, but I'm sure it still is in the latest release version. Either way, it's been fixed now, but thanks for pointing it out.
