### ISSUE TITLE
Crash after Rival Battle

### ISSUE THREAD

**Issue by deltabeard** [TheFakeMateo/RedPlusPlus#9]
Bugs with the first battle with Rival:
- No BG Music after rival sends out Pokemon (sound effects still play).
- No Levels shown.

![retroarch-0521-234944](https://cloud.githubusercontent.com/assets/3747104/15451243/1440e202-1fb0-11e6-827a-5cd9718c242f.png)

- Game crashes when battle ends, or when player uses item (white screen).

Other bugs:
- Graphical issues in Lab.

![retroarch-0521-234819](https://cloud.githubusercontent.com/assets/3747104/15451246/5d70497c-1fb0-11e6-8ad6-952e7a114573.png)

Issue found using Gambatte v0.5.0 via Retroarch. Using hard patch found [here](https://www.dropbox.com/s/cicyvz963uc948v/RedPlusPlus%20-%20Hard%20v2.3.ips?dl=0) with Pokemon Blue rom.

**Comment by TheFakeMateo** [comment]
You are supposed to use a Pokemon Red rom, not a Blue rom. Patch it to the correct rom instead and let me know if the problem persists, because neither of these issues show up in my original copies that I used to make the IPS patches.

**Comment by deltabeard** [comment]
Patched a Red rom instead and everything is working.

Thank you for your work.

**Comment by TheFakeMateo** [comment]
No problem, glad it turned out to be a simple fix (and glad for your sake that it turned up so early, and not halfway through the game or something).
